import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./layout.css";

import BackgroundGradient from "./src/components/BackgroundGradient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <BackgroundGradient /> */}
        <div className="header">
          <div className="header-left">
            <a href="#home">
              <div className="neonText">Aureliano Hubert Maximus</div>
            </a>
          </div>
          <div className="header-right">
            <a href="#resume">
              <div className="neonText">Resume</div>
            </a>
            <a href="#projects">
              <div className="neonText">Projects</div>
            </a>
            <a href="#contact">
              <div className="neonText">Contact</div>
            </a>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
